package avatar.voting;

import org.vertx.java.core.AsyncResult;
import org.vertx.java.core.eventbus.EventBus;
import org.vertx.java.core.json.JsonObject;
import org.vertx.java.platform.Verticle;

public class StarterVerticle extends Verticle {

    public static String AVATAR_PERSISTOR_ADDRESS = "avatar.persistor";

    @Override
    public void start() {

        JsonObject config = container.config();
        EventBus eventBus = vertx.eventBus();
        JsonObject jdbcPersistorConfig = config.getObject("data.persistor");

        container.deployModule("com.bloidonia~mod-jdbc-persistor~2.1.3",
                jdbcPersistorConfig, (AsyncResult<String> asyncResult) -> {
            if (asyncResult.succeeded()) {
                System.out.println("The mod-jdbc-persistor has been deployed, deployment ID is " + asyncResult.result());

                JsonObject message = new JsonObject()
                        .putString("action", "execute")
                        .putString("stmt", "CREATE TABLE IF NOT EXISTS voter "
                                + "(id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, "
                                + "email VARCHAR(500), CONSTRAINT voter_pk PRIMARY KEY(id))");

                eventBus.send(AVATAR_PERSISTOR_ADDRESS, message);

                message = new JsonObject()
                        .putString("action", "execute")
                        .putString("stmt", "CREATE TABLE IF NOT EXISTS suggestion "
                                + "(id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, "
                                + "name VARCHAR(500), votes INTEGER, CONSTRAINT suggestion_pk PRIMARY KEY(id))");

                eventBus.send(AVATAR_PERSISTOR_ADDRESS, message);

            } else {
                asyncResult.cause().printStackTrace();
            }
        });
        container.deployWorkerVerticle("avatar.voting.AvatarVotingVerticle", null, 4, false, (AsyncResult<String> asyncResult) -> {
            if (asyncResult.succeeded()) {
                System.out.println("AvatarVotingVerticle has been deployed, deployment ID is " + asyncResult.result());
            }
        });
    }
}
